[MachineDetails]
machine_name = frontier
machine_type = linux_x86_64
scheduler_type = k8s
cpus_per_node = 64
gpus_per_node = 8

[RepoDetails]
type_of_repository = git
git_data_transfer_protocol = ssh
git_machine_name = frontier
git_server_application_parent_dir = olcf-system-test/applications
git_ssh_server_url = gitlab@gitlab.ccs.ornl.gov
git_https_server_url = https://gitlab.ccs.ornl.gov

[TestshotDefaults]
batch_queue = batch
project_id = stf243
path_to_sspace = /ccs/proj/stf016/spock_test
system_log_tag = frontier_test
submit_args =

[SiteCustom]
kafka_uri = kafka.apps.gneiss.ccs.ornl.gov:30200
kafka_username = stf243_auser
kafka_events_topic = stf243.olcf-test-harness.events
kafka_metrics_topic = stf243.olcf-test-harness.metrics
kafka_node_health_topic = stf243.olcf-test-harness.node-health
kafka_db_type = druid
kafka_db_uri = https://druid-console.apps.gneiss.ccs.ornl.gov
kafka_ssl_ca_location = /sw/acceptance/olcf-test-harness-dev/configs/kafka_pems/cacerts.pem
kafka_ssl_certificate_location = /sw/acceptance/olcf-test-harness-dev/configs/kafka_pems/fullchain.pem
#kafka_dry_run = 1
# TODO -- must set kafka_password to enable Kafka logging
